### ISSUE TITLE
Error when trying to execute an update

### ISSUE THREAD

**Issue by System25** [gecos-team/gecoscc-ui#229]
Hi, if an administrator user tries to execute an update of the cookbook by uploading a ZIP file in /updates/add/ and there is no previous version of the gecos_ws_mgmt cookbook in Opscode Chef, the execution fails.

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 936, in handle_one_response
    self.run_application()
  File "/usr/local/lib/python2.7/site-packages/gevent/pywsgi.py", line 909, in run_application
    self.result = self.application(self.environ, self.start_response)
  File "/usr/local/lib/python2.7/site-packages/paste/translogger.py", line 68, in __call__
    return self.application(environ, replacement_start_response)
  File "/usr/local/lib/python2.7/site-packages/pyramid/router.py", line 272, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/usr/local/lib/python2.7/site-packages/pyramid/router.py", line 247, in invoke_subrequest
    response = handle_request(request)
  File "/usr/local/lib/python2.7/site-packages/pyramid/tweens.py", line 46, in excview_tween
    response = view_callable(exc, request)
  File "/usr/local/lib/python2.7/site-packages/pyramid/config/views.py", line 385, in viewresult_to_response
    result = view(context, request)
  File "/usr/local/lib/python2.7/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/usr/local/lib/python2.7/site-packages/pyramid/router.py", line 163, in handle_request
    response = view_callable(context, request)
  File "/usr/local/lib/python2.7/site-packages/pyramid/config/views.py", line 245, in _secured_view
    return view(context, request)
  File "/usr/local/lib/python2.7/site-packages/pyramid/config/views.py", line 355, in rendered_view
    result = view(context, request)
  File "/usr/local/lib/python2.7/site-packages/gecoscc/views/admins.py", line 273, in updates_add
    params = form.validate(controls)
  File "/usr/local/lib/python2.7/site-packages/gecoscc/forms.py", line 238, in validate
    return super(UpdateForm, self).validate(data)
  File "/usr/local/lib/python2.7/site-packages/deform/field.py", line 636, in validate
    return self.validate_pstruct(pstruct)
  File "/usr/local/lib/python2.7/site-packages/deform/field.py", line 671, in validate_pstruct
    appstruct = self.schema.deserialize(cstruct)
  File "/usr/local/lib/python2.7/site-packages/colander/__init__.py", line 1917, in deserialize
    appstruct = self.typ.deserialize(self, cstruct)
  File "/usr/local/lib/python2.7/site-packages/colander/__init__.py", line 604, in deserialize
    return self._impl(node, cstruct, callback)
  File "/usr/local/lib/python2.7/site-packages/colander/__init__.py", line 563, in _impl
    sub_result = callback(subnode, subval)
  File "/usr/local/lib/python2.7/site-packages/colander/__init__.py", line 602, in callback
    return subnode.deserialize(subcstruct)
  File "/usr/local/lib/python2.7/site-packages/colander/__init__.py", line 1939, in deserialize
    self.validator(self, appstruct)
  File "/usr/local/lib/python2.7/site-packages/colander/__init__.py", line 198, in __call__
    validator(node, value)
  File "/usr/local/lib/python2.7/site-packages/gecoscc/models.py", line 548, in __call__
    cookbook = get_cookbook(api, settings.get('chef.cookbook_name'))
  File "/usr/local/lib/python2.7/site-packages/gecoscc/utils.py", line 822, in get_cookbook
    return api['/cookbooks/%s/_latest/' % cookbook_name]
  File "/usr/local/lib/python2.7/site-packages/chef/api.py", line 221, in __getitem__
    return self.api_request('GET', path)
  File "/usr/local/lib/python2.7/site-packages/chef/api.py", line 217, in api_request
    response = self.request(method, path, headers, data)
  File "/usr/local/lib/python2.7/site-packages/chef/api.py", line 207, in request
    raise ChefServerError.from_error(response.reason, code=response.status_code)
ChefServerNotFoundError: Object Not Found
Wed Aug 28 08:04:17 2019 {'REMOTE_PORT': '44836', 'HTTP_HOST': '192.168.11.14', 'REMOTE_ADDR': '127.0.0.1', (hidden keys: 33)} failed with ChefServerNotFoundError
```

Best regards!

**Comment by alfem** [comment]
A basic installation of gecos-control-center MUST have a first cookbook loaded. So this is a very uncommon situation

**Comment by System25** [comment]
You are right, it's a very uncommon situation. But maybe a good idea to control this error for new installations or installations where someone makes a mistake when configuring "chef.cookbook_name" in the gecoscc.ini file.
